source "http://rubygems.org"

# Declare your gem's dependencies in how_to.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.

# jquery-rails is used by the dummy application
gem "jquery-rails"
gem 'bootstrap-sass'
gem 'sass-rails',   '~> 3.2.5'
gem 'mercury-rails'
gem 'how_to', :path => './lib/how_to_gem'
gem 'sqlite3'

# To use debugger
# gem 'debugger'
gem 'paperclip'