source "http://rubygems.org"

# Declare your gem's dependencies in how_to.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.

# jquery-rails is used by the dummy application
gem 'mercury-rails'
gem 'sqlite3'

